### ISSUE TITLE
Infografía_Realidad Aumentada (Eva Aguilar Avendaño)

### ISSUE THREAD

**Issue by Eva155** [SistemasTecTlaxiaco/infografia-Eva155#1]
[Infografía_Realidad Aumentada (Eva Aguilar Avendaño).pdf](https://github.com/SistemasTecTlaxiaco/infografia-Eva155/files/8055021/Infografia_Realidad.Aumentada.Eva.Aguilar.Avendano.pdf)

**Comment by 10154** [comment]
La infografía cuenta con una información enriquecida las referencias bibliográficas son confiables y se le asigna un puntaje de 20 % ya que cuenta con todos los aspectos de la rubrica.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
