### ISSUE TITLE
INFOGRAFÍA_INGENIERÍA DE REQUISITOS

### ISSUE THREAD

**Issue by Eva155** [SistemasTecTlaxiaco/infografia-Eva155#3]
![INFOGRAFIA_INGENIERÍA DE REQUISITOS_Eva Aguilar Avendaño](https://user-images.githubusercontent.com/72484110/109907912-3a9bdb80-7c9b-11eb-868f-d954c55aac8c.jpg)

**Comment by Nancy2050** [comment]
Calificación: 20%

Evaluó: Nancy Velasco Santiago

**Comment by josealfredo79** [comment]
Esta  bien hecho y revisado.
